/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class saki */

#ifndef _Included_saki
#define _Included_saki
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     saki
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_saki_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
